<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="QueryBizApplyStatusServiceService" targetNamespace="http://www.primeton.com/QueryBizApplyStatusService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:nns="http://www.primeton.com/QueryBizApplyStatusService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://www.primeton.com/QueryBizApplyStatusService" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:element name="queryBizApplyStatus">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="in0" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="queryBizApplyStatusResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="out1" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="queryBizApplyStatus">
    <wsdl:part name="queryBizApplyStatus" element="nns:queryBizApplyStatus">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="queryBizApplyStatusResponse">
    <wsdl:part name="queryBizApplyStatusResponse" element="nns:queryBizApplyStatusResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="QueryBizApplyStatusService">
    <wsdl:operation name="queryBizApplyStatus">
      <wsdl:input name="queryBizApplyStatus" message="nns:queryBizApplyStatus">
    </wsdl:input>
      <wsdl:output name="queryBizApplyStatusResponse" message="nns:queryBizApplyStatusResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
