<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CheckForCollImplServiceService" targetNamespace="http://www.primeton.com/CheckForCollImplService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:nns="http://www.primeton.com/CheckForCollImplService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://www.primeton.com/CheckForCollImplService" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:element name="checkForColl">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="in0" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="checkForCollResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="out1" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="checkForColl">
    <wsdl:part name="checkForColl" element="nns:checkForColl">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="checkForCollResponse">
    <wsdl:part name="checkForCollResponse" element="nns:checkForCollResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="CheckForCollImplService">
    <wsdl:operation name="checkForColl">
      <wsdl:input name="checkForColl" message="nns:checkForColl">
    </wsdl:input>
      <wsdl:output name="checkForCollResponse" message="nns:checkForCollResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
